[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "mod-rack"
dynamic = ["version"]
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pyside6>=6.10.1",
    "requests>=2.32.5",
    "tomli>=2.4.0",
    "websocket-client>=1.9.0",
    "websockets>=16.0",
]

[project.scripts]
mod-rack = "mod_rack.__main__:main"

[dependency-groups]
dev = [
    "mypy>=1.19.1",
    "pytest>=9.0.2",
    "ruff>=0.14.13",
    "toml>=0.10.2",
    "types-requests>=2.32.4.20260107",
]

[tool.hatch.version]
source = "vcs"

[tool.hatch.build.hooks.vcs]
version-file = "src/mod_rack/_version.py"
